baseurl: /my-trial-website
title: Abhinav Malhotra
subtitle: Personal Website
author: Abhinav Malhotra
simple_search: http://google.com/search
description: Post-doctoral researcher at University of Delaware
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination:
googleanalytics-id: UA-131196323-1
# plugins:
#   - jekyll-analytics
# jekyll_analytics:
#   GoogleAnalytics:          # Add, if you want to track with Google Analytics
#     id: UA-131196323-1       # Required - replace with your tracking id
#     anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking
